services:
  frontend:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080  # Point to backend
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      target: development
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/tmp  # Use anonymous volume for tmp
    environment:
      - GIN_MODE=debug
      - APPWRITE_ENDPOINT=${APPWRITE_ENDPOINT}
      - APPWRITE_PROJECT_ID=${APPWRITE_PROJECT_ID}
      - APPWRITE_API_KEY=${APPWRITE_API_KEY}