apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.name }}
  labels:
    {{- include "shrtn-charts.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: client
      {{- include "shrtn-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: client
        {{- include "shrtn-charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.client.name }}
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.client.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.client.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}