{{- if .Values.secrets.appwrite.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.appwrite.name }}
  labels:
    {{- include "shrtn-charts.labels" . | nindent 4 }}
type: Opaque
stringData:
  APPWRITE_ENDPOINT: {{ .Values.server.env.APPWRITE_ENDPOINT | quote }}
  APPWRITE_PROJECT_ID: {{ .Values.server.env.APPWRITE_PROJECT_ID | quote }}
  APPWRITE_API_KEY: {{ .Values.server.env.APPWRITE_API_KEY | quote }}
  APPWRITE_COLLECTION_ID: {{ .Values.server.env.APPWRITE_COLLECTION_ID | quote }}
  APPWRITE_DATABASE_ID: {{ .Values.server.env.APPWRITE_DATABASE_ID | quote }}
{{- end }}