apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.server.name }}
  labels:
    {{- include "shrtn-charts.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      {{- include "shrtn-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        {{- include "shrtn-charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.server.name }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.targetPort }}
              protocol: TCP
          env:
            - name: GIN_MODE
              value: {{ .Values.server.env.GIN_MODE | quote }}
            # These will come from the Secret
            - name: APPWRITE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.appwrite.name }}
                  key: APPWRITE_ENDPOINT
            - name: APPWRITE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.appwrite.name }}
                  key: APPWRITE_PROJECT_ID
            - name: APPWRITE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.appwrite.name }}
                  key: APPWRITE_API_KEY
            - name: APPWRITE_COLLECTION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.appwrite.name }}
                  key: APPWRITE_COLLECTION_ID
            - name: APPWRITE_DATABASE_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.appwrite.name }}
                  key: APPWRITE_DATABASE_ID
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}