apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}
  labels:
    {{- include "shrtn-charts.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: server
    {{- include "shrtn-charts.selectorLabels" . | nindent 4 }}